### ISSUE TITLE
Request for LDP Point Release

### ISSUE THREAD

**Issue by carrickr** [samvera/ldp#73]
We currently have Avalon 6.0 tracking #72 for the e-tags fix.  Can we request a point release for our production app so we don't have to track a specific git commit?

Thanks.

**Comment by jcoyne** [comment]
@carrickr sounds good to me.

**Comment by jcoyne** [comment]
@carrickr please do a PR to add yourself to https://github.com/projecthydra/hydra/blob/master/script/grant_revoke_gem_authority.rb#L19

**Comment by carrickr** [comment]
@jcoyne This is done, i assume this a prelude to having me cut the release?  I may need help with notes here.

**Comment by carrickr** [comment]
Stab at release notes for LDP 0.6.2 (this is based on all changes since 0.3 since that was the last time we had release notes):

- looser restrictions for RDF::Graphs, now requires only enumerable rather than graphable
- selective logging and performance metrics for http requests
- 409 errors now return LDP::conflict
- encode RDF in UTF-8 prior to turtle parsing 
- spaces no longer required between types
- byebug now supported for debugging in all environments 
- tests for Derby LDP
- RDF::Vocab::LDP used instead of LDP::URI
- LDP::Response now includes paging logic 
- 307 temporary redirect requests are followed
- use If-Unmodified-since instead of If-Match to avoid strong vs weak etag conflicts

**Comment by jcoyne** [comment]
@carrickr that sounds more like a 0.7.0 release than a 0.6 point release

**Comment by jcoyne** [comment]
@carrickr how are you getting all those things out of 3 commits? https://github.com/projecthydra/ldp/compare/v0.6.1...HEAD

**Comment by carrickr** [comment]
@jcoyne I was going from [0.3](https://github.com/projecthydra/ldp/releases) since we last had release notes for that.  Releases have been cut since then, but no notes, at least on the releases page.

I'm fine with calling a 0.7.0 though.  I was going with 0.6.2 since as you mentioned only three commits since 0.6.1.

**Comment by jcoyne** [comment]
@carrickr 0.6.2 seems fine now. But I would only make release notes for the commits since the last release or it will confuse people.

**Comment by carrickr** [comment]
@jcoyne 

notes would then just be:

- 307 temporary redirect requests are followed
- use If-Unmodified-since instead of If-Match to avoid strong vs weak etag conflicts
